# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('building_number', models.IntegerField(null=True)),
                ('flat_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=64)),
                ('email_type', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Private')], default='H', max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
                ('phone_type', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Private')], default='H', max_length=28)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephone_person', to='contacts.Person')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='person',
            field=models.ManyToManyField(related_name='groups_person', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_person', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_person', to='contacts.Person'),
        ),
    ]
