# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.EmailField(choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Private')], default='H', max_length=28),
        ),
    ]
